name: Currency Conversion Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 22 * * *"   # Runs daily at 22:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      XE_APP_URL: ${{ secrets.XE_APP_URL }}
      XE_API_KEY: ${{ secrets.XE_API_KEY }}
      XE_API_SECRET: ${{ secrets.XE_API_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install dependencies & run tests
        run: mvn clean test

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/extent-reports/
